"""add text_json to artifacttype

Revision ID: 019edcbb2029
Revises: 551deb4ca9b8
Create Date: 2025-09-08 16:19:28.047308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019edcbb2029'
down_revision: Union[str, Sequence[str], None] = '551deb4ca9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE artifact_type_enum ADD VALUE 'TEXT_JSON'")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
