"""add current_period_start to subscriptions

Revision ID: 23fae08153a1
Revises: 019edcbb2029
Create Date: 2025-09-23 20:46:21.165677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fae08153a1'
down_revision: Union[str, Sequence[str], None] = '019edcbb2029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'current_period_start')
    # ### end Alembic commands ###
