"""make stripe_subscription_id optional

Revision ID: 69425dba2fa9
Revises: 23fae08153a1
Create Date: 2025-09-25 14:38:08.444102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69425dba2fa9'
down_revision: Union[str, Sequence[str], None] = '23fae08153a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
