"""add completion_warnings and index created_at in projects

Revision ID: dd3d99ca1131
Revises: ff6586f9d6f0
Create Date: 2025-09-07 18:48:21.721075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3d99ca1131'
down_revision: Union[str, Sequence[str], None] = 'ff6586f9d6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('completion_warnings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'completion_warnings')
    # ### end Alembic commands ###
